model:
  name: SG_LLIE
  # 
  en_feature_num: 48
  en_inter_num: 32
  de_feature_num: 64
  de_inter_num: 32
  # NOTE 论文的图片只堆叠1个SAM,但是原始代码里堆叠2个
  sam_number: 2

training:
  total_iter: 60000
  batch_size: 2
  num_workers: 2
  # NOTE 随机裁剪大小
  gt_size: 256
  grad_clip: 0.01
  seed: 100

optimizer:
  type: Adam
  lr: 0.0002
  betas: [0.9, 0.999]

scheduler:
  type: CosineAnnealingRestartCyclicLR
  periods: [18400, 41600]
  restart_weights: [1, 1]
  eta_mins: [0.0003, 0.000001]

loss:
  # NOTE 权重来自于原论文
  charbonnier_weight: 1.0
  perceptual_weight: 0.01
  msssim_weight: 0.4
  use_pretrained_vgg: true
  # NOTE 只使用了VGG的第2层特征图来计算L1损失
  feature_layers: [2]

# 训练时数据增强 随机几何变换
augmentation:
  geometric: true

validation:
  val_freq: 5000
  save_img: true
  num_workers: 1
  metrics: [psnr, ssim]

testing:
  self_ensemble: false
  factor: 32

logging:
  print_freq: 20
  save_checkpoint_freq: 1000
  use_tb_logger: true
  # FIXME 路径有点问题
  log_dir: Refactor/logger/logs

paths:
  # FIXME 路径有点问题
  checkpoint_dir: checkpoints
  result_dir: Refactor/test/results
