model:
  name: SG_LLIE
  # 
  en_feature_num: 48
  en_inter_num: 32
  de_feature_num: 64
  de_inter_num: 32
  # NOTE 论文的图片只堆叠1个SAM,但是原始代码里堆叠2个
  sam_number: 2

training:
  total_iter: 60000
  batch_size: 2
  num_workers: 2
  # NOTE 随机裁剪大小
  # FIXME 如果不使用
  gt_size: 256
  grad_clip: 0.01
  seed: 100

optimizer:
  type: Adam
  lr: 0.0002
  betas: [0.9, 0.999]

scheduler:
  type: CosineAnnealingRestartCyclicLR
  periods: [18400, 41600]
  restart_weights: [1, 1]
  eta_mins: [0.0003, 0.000001]

loss:
  # NOTE 权重来自于原论文
  charbonnier_weight: 1.0
  perceptual_weight: 0.01
  msssim_weight: 0.4
  use_pretrained_vgg: true
  # NOTE 只使用了VGG的第2层特征图来计算L1损失
  feature_layers: [2]

# 训练时数据增强 随机几何变换
# NOTE 论文里没有提到数据增强,但是原始代码里有,所以我也加上了,但是效果不太好
augmentation:
  geometric: true

validation:
  # 每5000次迭代进行一次验证
  val_freq: 5000
  # 保存验证时的增强后图片,checkpoint_dir / "validation_images"
  # FIXME 路径有点问题
  save_img: true
  # 开 1 个子进程读验证数据
  num_workers: 1
  metrics: [psnr, ssim]

testing:
  # 测试时不使用数据增强
  self_ensemble: false
  factor: 32

logging:
  # 每20次迭代打印一次训练日志
  print_freq: 20
  # 每1000次迭代保存一次模型权重
  save_checkpoint_freq: 1000
  # 使用 TensorBoard 记录日志
  use_tb_logger: true
  # FIXME 路径有点问题
  log_dir: Refactor/logger/logs

paths:
  # FIXME 路径有点问题
  checkpoint_dir: checkpoints
  result_dir: Refactor/test/results
